### ISSUE TITLE
Problem with "multiple choices with comments" question type

### ISSUE THREAD

**Issue by GuiGuiSoft** [Shnoulle/skeletonquest#7]
Hello,

If I use the "Multiple choices with comments" question type, there is a bug (or at least, it seems to be a bug).
If I use the question preview and I select 2 answers, then the 1st answer is unchecked as I check the 2nd one. So the behavior looks like a "unique choice" question type.

Regards.

**Comment by Shnoulle** [comment]
Think it's not SkeletonQuest related : https://manual.limesurvey.org/Question_type_-_Multiple_choice_with_comments#Comment_only_when_..._.28commented_checkbox.29

Try with "No control on checkbox" . With the default behaviour : you have to fill inpyt:text to check the checkbox.

**Comment by GuiGuiSoft** [comment]
You are right, I didn't see this option.
Thanks !
